[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#2196F3"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showSidebarNavigation = false 